### PR TITLE
Update matchmacro.jl

### PR DESCRIPTION
**Pull request by ranjanan**
Fix deprecation warning

### CODE REVIEW

**Comment by kmsquire** [comment]
Sorry not to merge this sooner!  I'm inclined to, but it will require that the minimum version of Julia be changed to 0.4 in the REQUIRE file.  Can you add that change to this PR?

**Comment by tkelman** [comment]
Couldn't you throw a `@compat` on it? This seems really small to drop 0.3 over.

**Comment by ranjanan** [comment]
At the latest commit, I've just used the `@compat` as Tony suggested. Also, I'm not sure which version of `Compat` is required, I guess it's higher than 0.3. probably 0.6 or something.

**Comment by kmsquire** [comment]
Can you squash the commits?

**Comment by ranjanan** [comment]
Oh I'm sorry, I don't know how to do that. Is it essential?

**Comment by kmsquire** [comment]
Assuming you're using command line git, you would do

```bash
git rebase -i HEAD~4 # interactive rebase on the last 4 commits
# change "pick" to squash for commits 2-4
git push -f <github_remote> master
```

Also, as a general rule of thumb, it's a good idea to make changes on a branch instead of master, since then, your master branch and the master branch in the main repo might get out of sync if other PRs/commits are merged.

**Comment by kmsquire** [comment]
Fixed by b9eae9032

**Pull request closed without merging**
