### PR TITLE
Changed examples to match tuples due to expression change, updated so…

### PR DESCRIPTION
**Pull request by BCRARL**
…me examples, and changed tests. This adds some compliance with v0.7. tests no longer fail, but I'm not sure my hack getting arguments from expressions is the right one.

### CODE REVIEW

**Comment by sjoelund** [comment]
It seems there are more changes in 0.7:
* `ismatch(regex, str)` has been deprecated in favor of `contains(str, regex)`: https://github.com/JuliaLang/julia/pull/24673

And the assignment to Base.ismatch fails in Julia 1.0.0 (which I think would be better to target than 0.7 since the language should be much more stable).

**Comment by kmsquire** [comment]
Thanks for this!  I'll take a look, but in the mean time, you should consider looking at `Rematch.jl`, which mostly reimplements `Match.jl` in a cleaner way.

**Comment by BCRARL** [comment]
This is not a complete update to 0.7/1.0 . I just fixed the stuff so my own code worked :-( -- and the tests. 
0.7 is supposed to give us deprecation warnings. I received those for Range and included corrections for that. So by moving to 0.7 and then taking care of the deprecation warnings the code should be 1.0 compliant.
@kmsquire  I'll take a look at Rematch.jl Does this mean Match.jl should be deprecated?

**Comment by kmsquire** [comment]
Hi @BCRARL, thanks again for this merge request.  I ended up making a slightly different set of changes (e.g., the parens aren't necessary for handling guard expressions).

Regarding `Rematch.jl`, it's missing some functionality that's here, but it's written in a more modern style.  If I get around to it, I might update this code to match, but in the mean time, `Rematch.jl` works for you, it will probably be better maintained going into the future.

Cheers!

**Comment by BCRARL** [comment]
@kmsquire Thanks for updating. I'll consider Rematch.jl instead, although some of your choices fit my style better :-)

**Pull request closed without merging**
